/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HisabRouteImport } from './routes/hisab'
import { Route as HisabIndexRouteImport } from './routes/hisab.index'
import { Route as HisabActivityRouteImport } from './routes/hisab.activity'
import { Route as HisabCapitalRouteImport } from './routes/hisab.capital'
import { Route as HisabCustomersRouteImport } from './routes/hisab.customers'
import { Route as HisabFilesRouteImport } from './routes/hisab.files'
import { Route as HisabHelpRouteImport } from './routes/hisab.help'
import { Route as HisabListRouteImport } from './routes/hisab.list'
import { Route as HisabMoreRouteImport } from './routes/hisab.more'
import { Route as HisabNewRouteImport } from './routes/hisab.new'
import { Route as HisabPartiesRouteImport } from './routes/hisab.parties'
import { Route as HisabProductsRouteImport } from './routes/hisab.products'
import { Route as HisabReportsRouteImport } from './routes/hisab.reports'
import { Route as HisabSearchRouteImport } from './routes/hisab.search'
import { Route as HisabSettingsRouteImport } from './routes/hisab.settings'
import { Route as HisabStockRouteImport } from './routes/hisab.stock'
import { Route as HisabSuppliersRouteImport } from './routes/hisab.suppliers'
import { Route as HisabWarehouseStockRouteImport } from './routes/hisab.warehouse-stock'
import { Route as HisabWarehousesRouteImport } from './routes/hisab.warehouses'
import { Route as ApiHisabAdvancePaymentsRouteImport } from './routes/api/hisab/advance-payments'
import { Route as ApiHisabBankReconciliationRouteImport } from './routes/api/hisab/bank-reconciliation'
import { Route as ApiHisabCapitalRouteImport } from './routes/api/hisab/capital'
import { Route as ApiHisabCustomerDepositsRouteImport } from './routes/api/hisab/customer-deposits'
import { Route as ApiHisabCustomersRouteImport } from './routes/api/hisab/customers'
import { Route as ApiHisabDiscountsAlertsRouteImport } from './routes/api/hisab/discounts-alerts'
import { Route as ApiHisabReportsRouteImport } from './routes/api/hisab/reports'
import { Route as ApiHisabScanRouteImport } from './routes/api/hisab/scan'
import { Route as ApiHisabSearchRouteImport } from './routes/api/hisab/search'
import { Route as ApiHisabSuppliersRouteImport } from './routes/api/hisab/suppliers'
import { Route as ApiHisabWarehouseStockRouteImport } from './routes/api/hisab/warehouse-stock'
import { Route as ApiHisabWarehousesRouteImport } from './routes/api/hisab/warehouses'
import { Route as HisabCustomerIdRouteImport } from './routes/hisab.customer.$id'
import { Route as HisabInvoiceIdRouteImport } from './routes/hisab.invoice.$id'
import { Route as HisabSupplierIdRouteImport } from './routes/hisab.supplier.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HisabRoute = HisabRouteImport.update({
  id: '/hisab',
  path: '/hisab',
  getParentRoute: () => rootRouteImport,
} as any)
const HisabIndexRoute = HisabIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HisabRoute,
} as any)
const HisabActivityRoute = HisabActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => HisabRoute,
} as any)
const HisabCapitalRoute = HisabCapitalRouteImport.update({
  id: '/capital',
  path: '/capital',
  getParentRoute: () => HisabRoute,
} as any)
const HisabCustomersRoute = HisabCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => HisabRoute,
} as any)
const HisabFilesRoute = HisabFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => HisabRoute,
} as any)
const HisabHelpRoute = HisabHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => HisabRoute,
} as any)
const HisabListRoute = HisabListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => HisabRoute,
} as any)
const HisabMoreRoute = HisabMoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => HisabRoute,
} as any)
const HisabNewRoute = HisabNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => HisabRoute,
} as any)
const HisabPartiesRoute = HisabPartiesRouteImport.update({
  id: '/parties',
  path: '/parties',
  getParentRoute: () => HisabRoute,
} as any)
const HisabProductsRoute = HisabProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => HisabRoute,
} as any)
const HisabReportsRoute = HisabReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => HisabRoute,
} as any)
const HisabSearchRoute = HisabSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => HisabRoute,
} as any)
const HisabSettingsRoute = HisabSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => HisabRoute,
} as any)
const HisabStockRoute = HisabStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => HisabRoute,
} as any)
const HisabSuppliersRoute = HisabSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => HisabRoute,
} as any)
const HisabWarehouseStockRoute = HisabWarehouseStockRouteImport.update({
  id: '/warehouse-stock',
  path: '/warehouse-stock',
  getParentRoute: () => HisabRoute,
} as any)
const HisabWarehousesRoute = HisabWarehousesRouteImport.update({
  id: '/warehouses',
  path: '/warehouses',
  getParentRoute: () => HisabRoute,
} as any)
const ApiHisabAdvancePaymentsRoute = ApiHisabAdvancePaymentsRouteImport.update({
  id: '/api/hisab/advance-payments',
  path: '/api/hisab/advance-payments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHisabBankReconciliationRoute =
  ApiHisabBankReconciliationRouteImport.update({
    id: '/api/hisab/bank-reconciliation',
    path: '/api/hisab/bank-reconciliation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiHisabCapitalRoute = ApiHisabCapitalRouteImport.update({
  id: '/api/hisab/capital',
  path: '/api/hisab/capital',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHisabCustomerDepositsRoute =
  ApiHisabCustomerDepositsRouteImport.update({
    id: '/api/hisab/customer-deposits',
    path: '/api/hisab/customer-deposits',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiHisabCustomersRoute = ApiHisabCustomersRouteImport.update({
  id: '/api/hisab/customers',
  path: '/api/hisab/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHisabDiscountsAlertsRoute = ApiHisabDiscountsAlertsRouteImport.update({
  id: '/api/hisab/discounts-alerts',
  path: '/api/hisab/discounts-alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHisabReportsRoute = ApiHisabReportsRouteImport.update({
  id: '/api/hisab/reports',
  path: '/api/hisab/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHisabScanRoute = ApiHisabScanRouteImport.update({
  id: '/api/hisab/scan',
  path: '/api/hisab/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHisabSearchRoute = ApiHisabSearchRouteImport.update({
  id: '/api/hisab/search',
  path: '/api/hisab/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHisabSuppliersRoute = ApiHisabSuppliersRouteImport.update({
  id: '/api/hisab/suppliers',
  path: '/api/hisab/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHisabWarehouseStockRoute = ApiHisabWarehouseStockRouteImport.update({
  id: '/api/hisab/warehouse-stock',
  path: '/api/hisab/warehouse-stock',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHisabWarehousesRoute = ApiHisabWarehousesRouteImport.update({
  id: '/api/hisab/warehouses',
  path: '/api/hisab/warehouses',
  getParentRoute: () => rootRouteImport,
} as any)
const HisabCustomerIdRoute = HisabCustomerIdRouteImport.update({
  id: '/customer/$id',
  path: '/customer/$id',
  getParentRoute: () => HisabRoute,
} as any)
const HisabInvoiceIdRoute = HisabInvoiceIdRouteImport.update({
  id: '/invoice/$id',
  path: '/invoice/$id',
  getParentRoute: () => HisabRoute,
} as any)
const HisabSupplierIdRoute = HisabSupplierIdRouteImport.update({
  id: '/supplier/$id',
  path: '/supplier/$id',
  getParentRoute: () => HisabRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hisab': typeof HisabRouteWithChildren
  '/hisab/activity': typeof HisabActivityRoute
  '/hisab/capital': typeof HisabCapitalRoute
  '/hisab/customers': typeof HisabCustomersRoute
  '/hisab/files': typeof HisabFilesRoute
  '/hisab/help': typeof HisabHelpRoute
  '/hisab/list': typeof HisabListRoute
  '/hisab/more': typeof HisabMoreRoute
  '/hisab/new': typeof HisabNewRoute
  '/hisab/parties': typeof HisabPartiesRoute
  '/hisab/products': typeof HisabProductsRoute
  '/hisab/reports': typeof HisabReportsRoute
  '/hisab/search': typeof HisabSearchRoute
  '/hisab/settings': typeof HisabSettingsRoute
  '/hisab/stock': typeof HisabStockRoute
  '/hisab/suppliers': typeof HisabSuppliersRoute
  '/hisab/warehouse-stock': typeof HisabWarehouseStockRoute
  '/hisab/warehouses': typeof HisabWarehousesRoute
  '/hisab/': typeof HisabIndexRoute
  '/api/hisab/advance-payments': typeof ApiHisabAdvancePaymentsRoute
  '/api/hisab/bank-reconciliation': typeof ApiHisabBankReconciliationRoute
  '/api/hisab/capital': typeof ApiHisabCapitalRoute
  '/api/hisab/customer-deposits': typeof ApiHisabCustomerDepositsRoute
  '/api/hisab/customers': typeof ApiHisabCustomersRoute
  '/api/hisab/discounts-alerts': typeof ApiHisabDiscountsAlertsRoute
  '/api/hisab/reports': typeof ApiHisabReportsRoute
  '/api/hisab/scan': typeof ApiHisabScanRoute
  '/api/hisab/search': typeof ApiHisabSearchRoute
  '/api/hisab/suppliers': typeof ApiHisabSuppliersRoute
  '/api/hisab/warehouse-stock': typeof ApiHisabWarehouseStockRoute
  '/api/hisab/warehouses': typeof ApiHisabWarehousesRoute
  '/hisab/customer/$id': typeof HisabCustomerIdRoute
  '/hisab/invoice/$id': typeof HisabInvoiceIdRoute
  '/hisab/supplier/$id': typeof HisabSupplierIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hisab/activity': typeof HisabActivityRoute
  '/hisab/capital': typeof HisabCapitalRoute
  '/hisab/customers': typeof HisabCustomersRoute
  '/hisab/files': typeof HisabFilesRoute
  '/hisab/help': typeof HisabHelpRoute
  '/hisab/list': typeof HisabListRoute
  '/hisab/more': typeof HisabMoreRoute
  '/hisab/new': typeof HisabNewRoute
  '/hisab/parties': typeof HisabPartiesRoute
  '/hisab/products': typeof HisabProductsRoute
  '/hisab/reports': typeof HisabReportsRoute
  '/hisab/search': typeof HisabSearchRoute
  '/hisab/settings': typeof HisabSettingsRoute
  '/hisab/stock': typeof HisabStockRoute
  '/hisab/suppliers': typeof HisabSuppliersRoute
  '/hisab/warehouse-stock': typeof HisabWarehouseStockRoute
  '/hisab/warehouses': typeof HisabWarehousesRoute
  '/hisab': typeof HisabIndexRoute
  '/api/hisab/advance-payments': typeof ApiHisabAdvancePaymentsRoute
  '/api/hisab/bank-reconciliation': typeof ApiHisabBankReconciliationRoute
  '/api/hisab/capital': typeof ApiHisabCapitalRoute
  '/api/hisab/customer-deposits': typeof ApiHisabCustomerDepositsRoute
  '/api/hisab/customers': typeof ApiHisabCustomersRoute
  '/api/hisab/discounts-alerts': typeof ApiHisabDiscountsAlertsRoute
  '/api/hisab/reports': typeof ApiHisabReportsRoute
  '/api/hisab/scan': typeof ApiHisabScanRoute
  '/api/hisab/search': typeof ApiHisabSearchRoute
  '/api/hisab/suppliers': typeof ApiHisabSuppliersRoute
  '/api/hisab/warehouse-stock': typeof ApiHisabWarehouseStockRoute
  '/api/hisab/warehouses': typeof ApiHisabWarehousesRoute
  '/hisab/customer/$id': typeof HisabCustomerIdRoute
  '/hisab/invoice/$id': typeof HisabInvoiceIdRoute
  '/hisab/supplier/$id': typeof HisabSupplierIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hisab': typeof HisabRouteWithChildren
  '/hisab/activity': typeof HisabActivityRoute
  '/hisab/capital': typeof HisabCapitalRoute
  '/hisab/customers': typeof HisabCustomersRoute
  '/hisab/files': typeof HisabFilesRoute
  '/hisab/help': typeof HisabHelpRoute
  '/hisab/list': typeof HisabListRoute
  '/hisab/more': typeof HisabMoreRoute
  '/hisab/new': typeof HisabNewRoute
  '/hisab/parties': typeof HisabPartiesRoute
  '/hisab/products': typeof HisabProductsRoute
  '/hisab/reports': typeof HisabReportsRoute
  '/hisab/search': typeof HisabSearchRoute
  '/hisab/settings': typeof HisabSettingsRoute
  '/hisab/stock': typeof HisabStockRoute
  '/hisab/suppliers': typeof HisabSuppliersRoute
  '/hisab/warehouse-stock': typeof HisabWarehouseStockRoute
  '/hisab/warehouses': typeof HisabWarehousesRoute
  '/hisab/': typeof HisabIndexRoute
  '/api/hisab/advance-payments': typeof ApiHisabAdvancePaymentsRoute
  '/api/hisab/bank-reconciliation': typeof ApiHisabBankReconciliationRoute
  '/api/hisab/capital': typeof ApiHisabCapitalRoute
  '/api/hisab/customer-deposits': typeof ApiHisabCustomerDepositsRoute
  '/api/hisab/customers': typeof ApiHisabCustomersRoute
  '/api/hisab/discounts-alerts': typeof ApiHisabDiscountsAlertsRoute
  '/api/hisab/reports': typeof ApiHisabReportsRoute
  '/api/hisab/scan': typeof ApiHisabScanRoute
  '/api/hisab/search': typeof ApiHisabSearchRoute
  '/api/hisab/suppliers': typeof ApiHisabSuppliersRoute
  '/api/hisab/warehouse-stock': typeof ApiHisabWarehouseStockRoute
  '/api/hisab/warehouses': typeof ApiHisabWarehousesRoute
  '/hisab/customer/$id': typeof HisabCustomerIdRoute
  '/hisab/invoice/$id': typeof HisabInvoiceIdRoute
  '/hisab/supplier/$id': typeof HisabSupplierIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hisab'
    | '/hisab/activity'
    | '/hisab/capital'
    | '/hisab/customers'
    | '/hisab/files'
    | '/hisab/help'
    | '/hisab/list'
    | '/hisab/more'
    | '/hisab/new'
    | '/hisab/parties'
    | '/hisab/products'
    | '/hisab/reports'
    | '/hisab/search'
    | '/hisab/settings'
    | '/hisab/stock'
    | '/hisab/suppliers'
    | '/hisab/warehouse-stock'
    | '/hisab/warehouses'
    | '/hisab/'
    | '/api/hisab/advance-payments'
    | '/api/hisab/bank-reconciliation'
    | '/api/hisab/capital'
    | '/api/hisab/customer-deposits'
    | '/api/hisab/customers'
    | '/api/hisab/discounts-alerts'
    | '/api/hisab/reports'
    | '/api/hisab/scan'
    | '/api/hisab/search'
    | '/api/hisab/suppliers'
    | '/api/hisab/warehouse-stock'
    | '/api/hisab/warehouses'
    | '/hisab/customer/$id'
    | '/hisab/invoice/$id'
    | '/hisab/supplier/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/hisab/activity'
    | '/hisab/capital'
    | '/hisab/customers'
    | '/hisab/files'
    | '/hisab/help'
    | '/hisab/list'
    | '/hisab/more'
    | '/hisab/new'
    | '/hisab/parties'
    | '/hisab/products'
    | '/hisab/reports'
    | '/hisab/search'
    | '/hisab/settings'
    | '/hisab/stock'
    | '/hisab/suppliers'
    | '/hisab/warehouse-stock'
    | '/hisab/warehouses'
    | '/hisab'
    | '/api/hisab/advance-payments'
    | '/api/hisab/bank-reconciliation'
    | '/api/hisab/capital'
    | '/api/hisab/customer-deposits'
    | '/api/hisab/customers'
    | '/api/hisab/discounts-alerts'
    | '/api/hisab/reports'
    | '/api/hisab/scan'
    | '/api/hisab/search'
    | '/api/hisab/suppliers'
    | '/api/hisab/warehouse-stock'
    | '/api/hisab/warehouses'
    | '/hisab/customer/$id'
    | '/hisab/invoice/$id'
    | '/hisab/supplier/$id'
  id:
    | '__root__'
    | '/'
    | '/hisab'
    | '/hisab/activity'
    | '/hisab/capital'
    | '/hisab/customers'
    | '/hisab/files'
    | '/hisab/help'
    | '/hisab/list'
    | '/hisab/more'
    | '/hisab/new'
    | '/hisab/parties'
    | '/hisab/products'
    | '/hisab/reports'
    | '/hisab/search'
    | '/hisab/settings'
    | '/hisab/stock'
    | '/hisab/suppliers'
    | '/hisab/warehouse-stock'
    | '/hisab/warehouses'
    | '/hisab/'
    | '/api/hisab/advance-payments'
    | '/api/hisab/bank-reconciliation'
    | '/api/hisab/capital'
    | '/api/hisab/customer-deposits'
    | '/api/hisab/customers'
    | '/api/hisab/discounts-alerts'
    | '/api/hisab/reports'
    | '/api/hisab/scan'
    | '/api/hisab/search'
    | '/api/hisab/suppliers'
    | '/api/hisab/warehouse-stock'
    | '/api/hisab/warehouses'
    | '/hisab/customer/$id'
    | '/hisab/invoice/$id'
    | '/hisab/supplier/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HisabRoute: typeof HisabRouteWithChildren
  ApiHisabAdvancePaymentsRoute: typeof ApiHisabAdvancePaymentsRoute
  ApiHisabBankReconciliationRoute: typeof ApiHisabBankReconciliationRoute
  ApiHisabCapitalRoute: typeof ApiHisabCapitalRoute
  ApiHisabCustomerDepositsRoute: typeof ApiHisabCustomerDepositsRoute
  ApiHisabCustomersRoute: typeof ApiHisabCustomersRoute
  ApiHisabDiscountsAlertsRoute: typeof ApiHisabDiscountsAlertsRoute
  ApiHisabReportsRoute: typeof ApiHisabReportsRoute
  ApiHisabScanRoute: typeof ApiHisabScanRoute
  ApiHisabSearchRoute: typeof ApiHisabSearchRoute
  ApiHisabSuppliersRoute: typeof ApiHisabSuppliersRoute
  ApiHisabWarehouseStockRoute: typeof ApiHisabWarehouseStockRoute
  ApiHisabWarehousesRoute: typeof ApiHisabWarehousesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hisab': {
      id: '/hisab'
      path: '/hisab'
      fullPath: '/hisab'
      preLoaderRoute: typeof HisabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hisab/': {
      id: '/hisab/'
      path: '/'
      fullPath: '/hisab/'
      preLoaderRoute: typeof HisabIndexRouteImport
      parentRoute: typeof HisabRoute
    }
    '/hisab/activity': {
      id: '/hisab/activity'
      path: '/activity'
      fullPath: '/hisab/activity'
      preLoaderRoute: typeof HisabActivityRouteImport
      parentRoute: typeof HisabRoute
    }
    '/hisab/capital': {
      id: '/hisab/capital'
      path: '/capital'
      fullPath: '/hisab/capital'
      preLoaderRoute: typeof HisabCapitalRouteImport
      parentRoute: typeof HisabRoute
    }
    '/hisab/customers': {
      id: '/hisab/customers'
      path: '/customers'
      fullPath: '/hisab/customers'
      preLoaderRoute: typeof HisabCustomersRouteImport
      parentRoute: typeof HisabRoute
    }
    '/hisab/files': {
      id: '/hisab/files'
      path: '/files'
      fullPath: '/hisab/files'
      preLoaderRoute: typeof HisabFilesRouteImport
      parentRoute: typeof HisabRoute
    }
    '/hisab/help': {
      id: '/hisab/help'
      path: '/help'
      fullPath: '/hisab/help'
      preLoaderRoute: typeof HisabHelpRouteImport
      parentRoute: typeof HisabRoute
    }
    '/hisab/list': {
      id: '/hisab/list'
      path: '/list'
      fullPath: '/hisab/list'
      preLoaderRoute: typeof HisabListRouteImport
      parentRoute: typeof HisabRoute
    }
    '/hisab/more': {
      id: '/hisab/more'
      path: '/more'
      fullPath: '/hisab/more'
      preLoaderRoute: typeof HisabMoreRouteImport
      parentRoute: typeof HisabRoute
    }
    '/hisab/new': {
      id: '/hisab/new'
      path: '/new'
      fullPath: '/hisab/new'
      preLoaderRoute: typeof HisabNewRouteImport
      parentRoute: typeof HisabRoute
    }
    '/hisab/parties': {
      id: '/hisab/parties'
      path: '/parties'
      fullPath: '/hisab/parties'
      preLoaderRoute: typeof HisabPartiesRouteImport
      parentRoute: typeof HisabRoute
    }
    '/hisab/products': {
      id: '/hisab/products'
      path: '/products'
      fullPath: '/hisab/products'
      preLoaderRoute: typeof HisabProductsRouteImport
      parentRoute: typeof HisabRoute
    }
    '/hisab/reports': {
      id: '/hisab/reports'
      path: '/reports'
      fullPath: '/hisab/reports'
      preLoaderRoute: typeof HisabReportsRouteImport
      parentRoute: typeof HisabRoute
    }
    '/hisab/search': {
      id: '/hisab/search'
      path: '/search'
      fullPath: '/hisab/search'
      preLoaderRoute: typeof HisabSearchRouteImport
      parentRoute: typeof HisabRoute
    }
    '/hisab/settings': {
      id: '/hisab/settings'
      path: '/settings'
      fullPath: '/hisab/settings'
      preLoaderRoute: typeof HisabSettingsRouteImport
      parentRoute: typeof HisabRoute
    }
    '/hisab/stock': {
      id: '/hisab/stock'
      path: '/stock'
      fullPath: '/hisab/stock'
      preLoaderRoute: typeof HisabStockRouteImport
      parentRoute: typeof HisabRoute
    }
    '/hisab/suppliers': {
      id: '/hisab/suppliers'
      path: '/suppliers'
      fullPath: '/hisab/suppliers'
      preLoaderRoute: typeof HisabSuppliersRouteImport
      parentRoute: typeof HisabRoute
    }
    '/hisab/warehouse-stock': {
      id: '/hisab/warehouse-stock'
      path: '/warehouse-stock'
      fullPath: '/hisab/warehouse-stock'
      preLoaderRoute: typeof HisabWarehouseStockRouteImport
      parentRoute: typeof HisabRoute
    }
    '/hisab/warehouses': {
      id: '/hisab/warehouses'
      path: '/warehouses'
      fullPath: '/hisab/warehouses'
      preLoaderRoute: typeof HisabWarehousesRouteImport
      parentRoute: typeof HisabRoute
    }
    '/api/hisab/advance-payments': {
      id: '/api/hisab/advance-payments'
      path: '/api/hisab/advance-payments'
      fullPath: '/api/hisab/advance-payments'
      preLoaderRoute: typeof ApiHisabAdvancePaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hisab/bank-reconciliation': {
      id: '/api/hisab/bank-reconciliation'
      path: '/api/hisab/bank-reconciliation'
      fullPath: '/api/hisab/bank-reconciliation'
      preLoaderRoute: typeof ApiHisabBankReconciliationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hisab/capital': {
      id: '/api/hisab/capital'
      path: '/api/hisab/capital'
      fullPath: '/api/hisab/capital'
      preLoaderRoute: typeof ApiHisabCapitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hisab/customer-deposits': {
      id: '/api/hisab/customer-deposits'
      path: '/api/hisab/customer-deposits'
      fullPath: '/api/hisab/customer-deposits'
      preLoaderRoute: typeof ApiHisabCustomerDepositsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hisab/customers': {
      id: '/api/hisab/customers'
      path: '/api/hisab/customers'
      fullPath: '/api/hisab/customers'
      preLoaderRoute: typeof ApiHisabCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hisab/discounts-alerts': {
      id: '/api/hisab/discounts-alerts'
      path: '/api/hisab/discounts-alerts'
      fullPath: '/api/hisab/discounts-alerts'
      preLoaderRoute: typeof ApiHisabDiscountsAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hisab/reports': {
      id: '/api/hisab/reports'
      path: '/api/hisab/reports'
      fullPath: '/api/hisab/reports'
      preLoaderRoute: typeof ApiHisabReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hisab/scan': {
      id: '/api/hisab/scan'
      path: '/api/hisab/scan'
      fullPath: '/api/hisab/scan'
      preLoaderRoute: typeof ApiHisabScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hisab/search': {
      id: '/api/hisab/search'
      path: '/api/hisab/search'
      fullPath: '/api/hisab/search'
      preLoaderRoute: typeof ApiHisabSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hisab/suppliers': {
      id: '/api/hisab/suppliers'
      path: '/api/hisab/suppliers'
      fullPath: '/api/hisab/suppliers'
      preLoaderRoute: typeof ApiHisabSuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hisab/warehouse-stock': {
      id: '/api/hisab/warehouse-stock'
      path: '/api/hisab/warehouse-stock'
      fullPath: '/api/hisab/warehouse-stock'
      preLoaderRoute: typeof ApiHisabWarehouseStockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hisab/warehouses': {
      id: '/api/hisab/warehouses'
      path: '/api/hisab/warehouses'
      fullPath: '/api/hisab/warehouses'
      preLoaderRoute: typeof ApiHisabWarehousesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hisab/customer/$id': {
      id: '/hisab/customer/$id'
      path: '/customer/$id'
      fullPath: '/hisab/customer/$id'
      preLoaderRoute: typeof HisabCustomerIdRouteImport
      parentRoute: typeof HisabRoute
    }
    '/hisab/invoice/$id': {
      id: '/hisab/invoice/$id'
      path: '/invoice/$id'
      fullPath: '/hisab/invoice/$id'
      preLoaderRoute: typeof HisabInvoiceIdRouteImport
      parentRoute: typeof HisabRoute
    }
    '/hisab/supplier/$id': {
      id: '/hisab/supplier/$id'
      path: '/supplier/$id'
      fullPath: '/hisab/supplier/$id'
      preLoaderRoute: typeof HisabSupplierIdRouteImport
      parentRoute: typeof HisabRoute
    }
  }
}

interface HisabRouteChildren {
  HisabActivityRoute: typeof HisabActivityRoute
  HisabCapitalRoute: typeof HisabCapitalRoute
  HisabCustomersRoute: typeof HisabCustomersRoute
  HisabFilesRoute: typeof HisabFilesRoute
  HisabHelpRoute: typeof HisabHelpRoute
  HisabListRoute: typeof HisabListRoute
  HisabMoreRoute: typeof HisabMoreRoute
  HisabNewRoute: typeof HisabNewRoute
  HisabPartiesRoute: typeof HisabPartiesRoute
  HisabProductsRoute: typeof HisabProductsRoute
  HisabReportsRoute: typeof HisabReportsRoute
  HisabSearchRoute: typeof HisabSearchRoute
  HisabSettingsRoute: typeof HisabSettingsRoute
  HisabStockRoute: typeof HisabStockRoute
  HisabSuppliersRoute: typeof HisabSuppliersRoute
  HisabWarehouseStockRoute: typeof HisabWarehouseStockRoute
  HisabWarehousesRoute: typeof HisabWarehousesRoute
  HisabIndexRoute: typeof HisabIndexRoute
  HisabCustomerIdRoute: typeof HisabCustomerIdRoute
  HisabInvoiceIdRoute: typeof HisabInvoiceIdRoute
  HisabSupplierIdRoute: typeof HisabSupplierIdRoute
}

const HisabRouteChildren: HisabRouteChildren = {
  HisabActivityRoute: HisabActivityRoute,
  HisabCapitalRoute: HisabCapitalRoute,
  HisabCustomersRoute: HisabCustomersRoute,
  HisabFilesRoute: HisabFilesRoute,
  HisabHelpRoute: HisabHelpRoute,
  HisabListRoute: HisabListRoute,
  HisabMoreRoute: HisabMoreRoute,
  HisabNewRoute: HisabNewRoute,
  HisabPartiesRoute: HisabPartiesRoute,
  HisabProductsRoute: HisabProductsRoute,
  HisabReportsRoute: HisabReportsRoute,
  HisabSearchRoute: HisabSearchRoute,
  HisabSettingsRoute: HisabSettingsRoute,
  HisabStockRoute: HisabStockRoute,
  HisabSuppliersRoute: HisabSuppliersRoute,
  HisabWarehouseStockRoute: HisabWarehouseStockRoute,
  HisabWarehousesRoute: HisabWarehousesRoute,
  HisabIndexRoute: HisabIndexRoute,
  HisabCustomerIdRoute: HisabCustomerIdRoute,
  HisabInvoiceIdRoute: HisabInvoiceIdRoute,
  HisabSupplierIdRoute: HisabSupplierIdRoute,
}

const HisabRouteWithChildren = HisabRoute._addFileChildren(HisabRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HisabRoute: HisabRouteWithChildren,
  ApiHisabAdvancePaymentsRoute: ApiHisabAdvancePaymentsRoute,
  ApiHisabBankReconciliationRoute: ApiHisabBankReconciliationRoute,
  ApiHisabCapitalRoute: ApiHisabCapitalRoute,
  ApiHisabCustomerDepositsRoute: ApiHisabCustomerDepositsRoute,
  ApiHisabCustomersRoute: ApiHisabCustomersRoute,
  ApiHisabDiscountsAlertsRoute: ApiHisabDiscountsAlertsRoute,
  ApiHisabReportsRoute: ApiHisabReportsRoute,
  ApiHisabScanRoute: ApiHisabScanRoute,
  ApiHisabSearchRoute: ApiHisabSearchRoute,
  ApiHisabSuppliersRoute: ApiHisabSuppliersRoute,
  ApiHisabWarehouseStockRoute: ApiHisabWarehouseStockRoute,
  ApiHisabWarehousesRoute: ApiHisabWarehousesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
